services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
      build: .
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000
      volumes:
        - ./app:/app/app
        - ./requirements.txt:/app/requirements.txt
      environment:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=postgres
        - DB_NAME=${DB_NAME}
      ports:
        - "${DB_PORT}:8000"
      depends_on:
        - postgres

volumes:
  postgres_data: